### ISSUE TITLE
undefined method 'init_admin'

### ISSUE THREAD

**Issue by chussenot** [Crecto/crecto-admin#31]
Hi @fridgerator @jianghengle 
I just follow your exemple but I've an error and the `self.init_admin()` can't be loaded.
Any ideas to fix that?

(╯°□°）╯︵ ┻━┻

### shards.yml

```yaml
name: mesh-manager
version: 0.1.0

dependencies:
  kemal:
    github: kemalcr/kemal
  sqlite3:
    github: crystal-lang/crystal-sqlite3
  crecto:
    github: fridgerator/crecto
  crecto-admin:
    github: Crecto/crecto-admin

targets:
  mesh-manager:
    main: src/mesh-manager.cr

crystal: 0.26.0

license: MIT

```

### src/app.cr

```crystal
require "kemal"
require "sqlite3"
require "crecto"
require "crecto-admin"

module Mesh::Manager
  VERSION = "0.1.0"
end

module Repo
    extend Crecto::Repo
    
    config do |conf|
        conf.adapter = Crecto::Adapters::Postgres
        conf.hostname = "localhost"
        conf.database = "my_database"
    end
end

class User < Crecto::Model
    schema "users" do # table name
        field :first_name, String
        field :last_name, String
    end
    
    validate_required [:first_name, :last_name]
end

init_admin()

admin_resource(User, Repo)

Kemal::Session.config do |config|
  config.secret = "sasd8za0843efqxcr79sad8saet"
end

Kemal.run

```

<img src="https://i.imgur.com/9WNtUjg.png" />

**Comment by jianghengle** [comment]
I think you installed the crecto-admin at version 0.1.0, since that is the only release there. We probably will release the current one later. Meanwhile, you could specify the branch to check out the latest code 
```
  crecto-admin:
    github: Crecto/crecto-admin
    branch: master
```
which should have the `init_admin` method. You should check the `lib` directory after install shards.

By the way, I noticed you are using `crystal: 0.26.0`. The current master branch is tested against `0.25.1`, which I am not sure whether it will fully work with the `0.26.0`. You could debug it yourself.

You also have the wrong adapter `conf.adapter = Crecto::Adapters::Postgres` in your code, which should be `Crecto::Adatperes::SQLite3` as indicated in your `shard.yml` and `require ...`.

**Comment by chussenot** [comment]
Thx for this answer, it's fix

```yaml
version: 0.1.0
dependencies:
  kemal:
    github: kemalcr/kemal
  sqlite3:
    github: crystal-lang/crystal-sqlite3
  crecto-admin:
    github: Crecto/crecto-admin
  crecto:
    github: crecto/crecto
    version: 0.9.0
  kemal-session:
    github: kemalcr/kemal-session
    version: 0.10.0
  micrate:
    github: amberframework/micrate

targets:
  mesh-manager:
    main: src/mesh-manager.cr

crystal: 0.26.0

license: MIT

```
